/* NZK internationalization */
(() => {
    const STORAGE_KEY = "nzk_language";
    const DICTS = {
        "pt-BR": window.NZK_I18N_PT_BR || {},
        "en-US": window.NZK_I18N_EN_US || {},
        "es-ES": window.NZK_I18N_ES_ES || {},
        "fr-FR": window.NZK_I18N_FR_FR || {},
        "ja-JP": window.NZK_I18N_JA_JP || {}
    };

    const textSources = new WeakMap();
    const attrSources = new WeakMap();
    let currentLanguage = localStorage.getItem(STORAGE_KEY) || "pt-BR";
    let applying = false;
    let observer = null;
    const originalTitle = document.title;

    // Dynamic strings generated by dashboard.js — one rule table per language,
    // applied in order. Adding a new language only means adding a new key here.
    const dynamicRules = {
        "en-US": [
            [/^⚠️ Bot removido há (\d+)d$/, "⚠️ Bot removed $1d ago"],
            [/^Lvl (\d+)$/, "Lvl $1"],
            [/^Level (\d+)$/, "Level $1"],
            [/^Cargo removido \((.+)\)$/, "Role removed ($1)"],
            [/^⏳ Esse status volta ao padrão em (.+)\.$/, "⏳ This status returns to default at $1."],
            [/^Selecione um membro para ver o histórico\.$/, "Select a member to view history."],
            [/^\+\s*(\d+) XP$/, "+$1 XP"]
        ],
        "es-ES": [
            [/^⚠️ Bot removido há (\d+)d$/, "⚠️ Bot eliminado hace $1d"],
            [/^Lvl (\d+)$/, "Nvl $1"],
            [/^Level (\d+)$/, "Nivel $1"],
            [/^Cargo removido \((.+)\)$/, "Rol eliminado ($1)"],
            [/^⏳ Esse status volta ao padrão em (.+)\.$/, "⏳ Este estado vuelve al valor predeterminado en $1."],
            [/^Selecione um membro para ver o histórico\.$/, "Selecciona un miembro para ver el historial."],
            [/^\+\s*(\d+) XP$/, "+$1 XP"]
        ],
        "fr-FR": [
            [/^⚠️ Bot removido há (\d+)d$/, "⚠️ Bot retiré il y a $1j"],
            [/^Lvl (\d+)$/, "Niv $1"],
            [/^Level (\d+)$/, "Niveau $1"],
            [/^Cargo removido \((.+)\)$/, "Rôle supprimé ($1)"],
            [/^⏳ Esse status volta ao padrão em (.+)\.$/, "⏳ Ce statut revient à sa valeur par défaut à $1."],
            [/^Selecione um membro para ver o histórico\.$/, "Sélectionnez un membre pour voir l'historique."],
            [/^\+\s*(\d+) XP$/, "+$1 XP"]
        ],
        "ja-JP": [
            [/^⚠️ Bot removido há (\d+)d$/, "⚠️ Botが削除されました: $1日"],
            [/^Lvl (\d+)$/, "レベル $1"],
            [/^Level (\d+)$/, "レベル $1"],
            [/^Cargo removido \((.+)\)$/, "ロールが削除されました ($1)"],
            [/^⏳ Esse status volta ao padrão em (.+)\.$/, "⏳ このステータスは $1 にデフォルトに戻ります。"],
            [/^Selecione um membro para ver o histórico\.$/, "履歴を表示するにはメンバーを選択してください。"],
            [/^\+\s*(\d+) XP$/, "+$1 XP"]
        ]
    };

    function applyDynamicRules(text) {
        const rules = dynamicRules[currentLanguage];
        if (!rules) return text;
        return rules.reduce((acc, [regex, replacement]) => acc.replace(regex, replacement), text);
    }

    function translateText(source) {
        if (!source) return source;
        const dict = DICTS[currentLanguage] || DICTS["pt-BR"];

        // Preserve leading/trailing whitespace while translating the actual text.
        const match = source.match(/^(\s*)([\s\S]*?)(\s*)$/);
        const core = match ? match[2] : source;
        let translated = dict[core] ?? core;

        translated = applyDynamicRules(translated);

        return match ? `${match[1]}${translated}${match[3]}` : translated;
    }

    function translateAttributes(root = document) {
        root.querySelectorAll?.("[data-i18n-placeholder], [data-i18n-title], [data-i18n-aria-label]").forEach(el => {
            if (el.hasAttribute("data-i18n-placeholder")) {
                el.placeholder = translateKey(el.dataset.i18nPlaceholder, el.placeholder);
            }
            if (el.hasAttribute("data-i18n-title")) {
                el.title = translateKey(el.dataset.i18nTitle, el.title);
            }
            if (el.hasAttribute("data-i18n-aria-label")) {
                el.setAttribute("aria-label", translateKey(el.dataset.i18nAriaLabel, el.getAttribute("aria-label") || ""));
            }
        });
    }

    const keyTranslations = {
        "label.language": { "pt-BR": "Idioma", "en-US": "Language", "es-ES": "Idioma", "fr-FR": "Langue", "ja-JP": "言語" },
        "btn.logout": { "pt-BR": "Sair", "en-US": "Log out", "es-ES": "Cerrar sesión", "fr-FR": "Déconnexion", "ja-JP": "ログアウト" },
        "realtime.title": { "pt-BR": "Atualizações em tempo real ativas", "en-US": "Real-time updates active", "es-ES": "Actualizaciones en tiempo real activas", "fr-FR": "Mises à jour en temps réel actives", "ja-JP": "リアルタイム更新が有効です" },
        "placeholder.status": { "pt-BR": "Ex: 🛡️ Protegendo Nazarick", "en-US": "E.g.: 🛡️ Protecting Nazarick", "es-ES": "Ej.: 🛡️ Protegiendo Nazarick", "fr-FR": "Ex. : 🛡️ Protège Nazarick", "ja-JP": "例: 🛡️ ナザリックを護衛中" },
        "placeholder.levelup": { "pt-BR": "{usuario} >> **{nivel}**", "en-US": "{user} >> **{level}**", "es-ES": "{usuario} >> **{nivel}**", "fr-FR": "{usuario} >> **{nivel}**", "ja-JP": "{usuario} >> **{nivel}**" },
        "placeholder.welcome": { "pt-BR": "Bem-vindo(a) ao {servidor}, {usuario}!", "en-US": "Welcome to {server}, {user}!", "es-ES": "¡Bienvenido(a) a {servidor}, {usuario}!", "fr-FR": "Bienvenue sur {servidor}, {usuario} !", "ja-JP": "{servidor} へようこそ、{usuario}！" },
        "placeholder.boost": { "pt-BR": "{usuario} acabou de impulsionar o servidor! Obrigado pelo apoio!", "en-US": "{usuario} just boosted the server! Thanks for the support!", "es-ES": "¡{usuario} acaba de impulsar el servidor! ¡Gracias por el apoyo!", "fr-FR": "{usuario} vient de booster le serveur ! Merci pour le soutien !", "ja-JP": "{usuario} がサーバーをブーストしました！サポートありがとうございます！" },
        "placeholder.youtubeId": { "pt-BR": "@handle, UCxxxx ou URL", "en-US": "@handle, UCxxxx or URL", "es-ES": "@handle, UCxxxx o URL", "fr-FR": "@pseudo, UCxxxx ou URL", "ja-JP": "@ハンドル、UCxxxx または URL" },
        "placeholder.youtubeName": { "pt-BR": "Ex: Nazarick TV", "en-US": "E.g.: Nazarick TV", "es-ES": "Ej.: Nazarick TV", "fr-FR": "Ex. : Nazarick TV", "ja-JP": "例: ナザリックTV" },
        "placeholder.twitchUser": { "pt-BR": "ex: nomeaqui", "en-US": "e.g.: username", "es-ES": "ej.: nombreaqui", "fr-FR": "ex. : nomici", "ja-JP": "例: ユーザー名" },
        "placeholder.searchMember": { "pt-BR": "🔍 Buscar membro...", "en-US": "🔍 Search member...", "es-ES": "🔍 Buscar miembro...", "fr-FR": "🔍 Rechercher un membre...", "ja-JP": "🔍 メンバーを検索..." },
        "placeholder.levelExample": { "pt-BR": "Ex: 5", "en-US": "E.g.: 5", "es-ES": "Ej.: 5", "fr-FR": "Ex. : 5", "ja-JP": "例: 5" }
    };

    function translateKey(key, fallback="") {
        return keyTranslations[key]?.[currentLanguage] ?? fallback;
    }

    function walkTextNodes(root = document.body) {
        if (!root) return;
        const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
        const nodes = [];
        let n;
        while ((n = walker.nextNode())) nodes.push(n);

        applying = true;
        nodes.forEach(node => {
            let source = textSources.get(node);
            if (source == null) {
                source = node.nodeValue || "";
                textSources.set(node, source);
            }
            node.nodeValue = translateText(source);
        });

        // Attributes without explicit keys are tracked by the engine so dynamic UI can translate too.
        root.querySelectorAll?.("input, textarea, button, select, option, [title], [aria-label]").forEach(el => {
            ["placeholder", "title", "aria-label"].forEach(attr => {
                if (!el.hasAttribute(attr)) return;
                let sources = attrSources.get(el);
                if (!sources) {
                    sources = {};
                    attrSources.set(el, sources);
                }
                if (sources[attr] == null) sources[attr] = el.getAttribute(attr) || "";
                const dictValue = DICTS[currentLanguage]?.[sources[attr]];
                if (dictValue != null) el.setAttribute(attr, dictValue);
            });
        });

        translateAttributes(root);
        applying = false;
    }

    function translate() {
        document.title = translateText(originalTitle);
        const langAttr = { "pt-BR": "pt-BR", "en-US": "en", "es-ES": "es", "fr-FR": "fr", "ja-JP": "ja" };
        document.documentElement.lang = langAttr[currentLanguage] || "pt-BR";
        document.querySelectorAll("[data-language-select]").forEach(select => {
            select.value = currentLanguage;
        });

        // Avoid treating our own translated text as a new source string.
        if (observer) observer.disconnect();
        walkTextNodes(document.body);
        if (observer) {
            observer.observe(document.body, {
                subtree: true,
                childList: true,
                characterData: true
            });
        }

        window.dispatchEvent(new CustomEvent("nzk-language-changed", {
            detail: { language: currentLanguage }
        }));
    }

    function setLanguage(language) {
        if (!DICTS[language]) return;
        currentLanguage = language;
        localStorage.setItem(STORAGE_KEY, language);
        translate();
    }

    function init() {
        document.querySelectorAll("[data-language-select]").forEach(select => {
            select.addEventListener("change", e => setLanguage(e.target.value));
        });

        // Dynamic dashboard content is inserted after login and after API calls.
        observer = new MutationObserver(records => {
            if (applying) return;

            records.forEach(record => {
                if (record.type === "characterData") {
                    // If application code changed an existing text node, that new value
                    // is the source language string.
                    textSources.set(record.target, record.target.nodeValue || "");
                } else {
                    record.addedNodes.forEach(node => {
                        if (node.nodeType === Node.TEXT_NODE) {
                            textSources.set(node, node.nodeValue || "");
                        }
                    });
                }
            });

            observer.disconnect();
            walkTextNodes(document.body);
            observer.observe(document.body, {
                subtree: true,
                childList: true,
                characterData: true
            });
        });

        observer.observe(document.body, {
            subtree: true,
            childList: true,
            characterData: true
        });

        translate();
    }

    window.NZKI18n = {
        get language() { return currentLanguage; },
        setLanguage,
        translate,
        t: (text) => translateText(text)
    };

    // Make t() convenient for dashboard.js additions/edits.
    window.t = (text) => translateText(text);

    if (document.readyState === "loading") {
        document.addEventListener("DOMContentLoaded", init, { once: true });
    } else {
        init();
    }
})();