/* NZK internationalization */
(() => {
    const STORAGE_KEY = "nzk_language";
    const DICTS = {
        "pt-BR": window.NZK_I18N_PT_BR || {},
        "en-US": window.NZK_I18N_EN_US || {},
        "es-ES": window.NZK_I18N_ES_ES || {}
    };

    const textSources = new WeakMap();
    const attrSources = new WeakMap();
    let currentLanguage = localStorage.getItem(STORAGE_KEY) || "pt-BR";
    let applying = false;
    let observer = null;
    const originalTitle = document.title;

    function escapeRegex(s) {
        return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    }

    function translateText(source) {
        if (!source) return source;
        const dict = DICTS[currentLanguage] || DICTS["pt-BR"];

        // Preserve leading/trailing whitespace while translating the actual text.
        const match = source.match(/^(\s*)([\s\S]*?)(\s*)$/);
        const core = match ? match[2] : source;
        let translated = dict[core] ?? core;

        // Dynamic strings generated by dashboard.js.
        if (currentLanguage === "en-US") {
            translated = translated
                .replace(/^⚠️ Bot removido há (\d+)d$/, "⚠️ Bot removed $1d ago")
                .replace(/^Lvl (\d+)$/, "Lvl $1")
                .replace(/^Level (\d+)$/, "Level $1")
                .replace(/^Cargo removido \((.+)\)$/, "Role removed ($1)")
                .replace(/^⏳ Esse status volta ao padrão em (.+)\.$/, "⏳ This status returns to default at $1.")
                .replace(/^Selecione um membro para ver o histórico\.$/, "Select a member to view history.")
                .replace(/^\+\s*(\d+) XP$/, "+$1 XP");
        }

        if (currentLanguage === "es-ES") {
            translated = translated
                .replace(/^⚠️ Bot removido há (\d+)d$/, "⚠️ Bot eliminado hace $1d")
                .replace(/^Lvl (\d+)$/, "Nvl $1")
                .replace(/^Level (\d+)$/, "Nivel $1")
                .replace(/^Cargo removido \((.+)\)$/, "Rol eliminado ($1)")
                .replace(/^⏳ Esse status volta ao padrão em (.+)\.$/, "⏳ Este estado vuelve al valor predeterminado en $1.")
                .replace(/^Selecione um membro para ver o histórico\.$/, "Selecciona un miembro para ver el historial.")
                .replace(/^\+\s*(\d+) XP$/, "+$1 XP");
        }

        return match ? `${match[1]}${translated}${match[3]}` : translated;
    }

    function translateAttributes(root = document) {
        root.querySelectorAll?.("[data-i18n-placeholder], [data-i18n-title], [data-i18n-aria-label]").forEach(el => {
            if (el.hasAttribute("data-i18n-placeholder")) {
                el.placeholder = translateKey(el.dataset.i18nPlaceholder, el.placeholder);
            }
            if (el.hasAttribute("data-i18n-title")) {
                el.title = translateKey(el.dataset.i18nTitle, el.title);
            }
            if (el.hasAttribute("data-i18n-aria-label")) {
                el.setAttribute("aria-label", translateKey(el.dataset.i18nAriaLabel, el.getAttribute("aria-label") || ""));
            }
        });
    }

    const keyTranslations = {
        "label.language": { "pt-BR": "Idioma", "en-US": "Language", "es-ES": "Idioma" },
        "btn.logout": { "pt-BR": "Sair", "en-US": "Log out", "es-ES": "Cerrar sesión" },
        "realtime.title": { "pt-BR": "Atualizações em tempo real ativas", "en-US": "Real-time updates active", "es-ES": "Actualizaciones en tiempo real activas" },
        "placeholder.status": { "pt-BR": "Ex: 🛡️ Protegendo Nazarick", "en-US": "E.g.: 🛡️ Protecting Nazarick", "es-ES": "Ej.: 🛡️ Protegiendo Nazarick" },
        "placeholder.levelup": { "pt-BR": "{usuario} >> **{nivel}**", "en-US": "{user} >> **{level}**", "es-ES": "{usuario} >> **{nivel}**" },
        "placeholder.welcome": { "pt-BR": "Bem-vindo(a) ao {servidor}, {usuario}!", "en-US": "Welcome to {server}, {user}!", "es-ES": "¡Bienvenido(a) a {servidor}, {usuario}!" },
        "placeholder.boost": { "pt-BR": "{usuario} acabou de impulsionar o servidor! Obrigado pelo apoio!", "en-US": "{usuario} just boosted the server! Thanks for the support!", "es-ES": "¡{usuario} acaba de impulsar el servidor! ¡Gracias por el apoyo!" },
        "placeholder.youtubeId": { "pt-BR": "@handle, UCxxxx ou URL", "en-US": "@handle, UCxxxx or URL", "es-ES": "@handle, UCxxxx o URL" },
        "placeholder.youtubeName": { "pt-BR": "Ex: Nazarick TV", "en-US": "E.g.: Nazarick TV", "es-ES": "Ej.: Nazarick TV" },
        "placeholder.twitchUser": { "pt-BR": "ex: nomeaqui", "en-US": "e.g.: username", "es-ES": "ej.: nombreaqui" },
        "placeholder.searchMember": { "pt-BR": "🔍 Buscar membro...", "en-US": "🔍 Search member...", "es-ES": "🔍 Buscar miembro..." },
        "placeholder.levelExample": { "pt-BR": "Ex: 5", "en-US": "E.g.: 5", "es-ES": "Ej.: 5" }
    };

    function translateKey(key, fallback="") {
        return keyTranslations[key]?.[currentLanguage] ?? fallback;
    }

    function walkTextNodes(root = document.body) {
        if (!root) return;
        const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
        const nodes = [];
        let n;
        while ((n = walker.nextNode())) nodes.push(n);

        applying = true;
        nodes.forEach(node => {
            let source = textSources.get(node);
            if (source == null) {
                source = node.nodeValue || "";
                textSources.set(node, source);
            }
            node.nodeValue = translateText(source);
        });

        // Attributes without explicit keys are tracked by the engine so dynamic UI can translate too.
        root.querySelectorAll?.("input, textarea, button, select, option, [title], [aria-label]").forEach(el => {
            ["placeholder", "title", "aria-label"].forEach(attr => {
                if (!el.hasAttribute(attr)) return;
                let sources = attrSources.get(el);
                if (!sources) {
                    sources = {};
                    attrSources.set(el, sources);
                }
                if (sources[attr] == null) sources[attr] = el.getAttribute(attr) || "";
                const dictValue = DICTS[currentLanguage]?.[sources[attr]];
                if (dictValue != null) el.setAttribute(attr, dictValue);
            });
        });

        translateAttributes(root);
        applying = false;
    }

    function translate() {
        document.title = translateText(originalTitle);
        document.documentElement.lang = currentLanguage === "en-US" ? "en" : "pt-BR";
        document.querySelectorAll("[data-language-select]").forEach(select => {
            select.value = currentLanguage;
        });

        // Avoid treating our own translated text as a new source string.
        if (observer) observer.disconnect();
        walkTextNodes(document.body);
        if (observer) {
            observer.observe(document.body, {
                subtree: true,
                childList: true,
                characterData: true
            });
        }

        window.dispatchEvent(new CustomEvent("nzk-language-changed", {
            detail: { language: currentLanguage }
        }));
    }

    function setLanguage(language) {
        if (!DICTS[language]) return;
        currentLanguage = language;
        localStorage.setItem(STORAGE_KEY, language);
        translate();
    }

    function init() {
        document.querySelectorAll("[data-language-select]").forEach(select => {
            select.addEventListener("change", e => setLanguage(e.target.value));
        });

        // Dynamic dashboard content is inserted after login and after API calls.
        observer = new MutationObserver(records => {
            if (applying) return;

            records.forEach(record => {
                if (record.type === "characterData") {
                    // If application code changed an existing text node, that new value
                    // is the source language string.
                    textSources.set(record.target, record.target.nodeValue || "");
                } else {
                    record.addedNodes.forEach(node => {
                        if (node.nodeType === Node.TEXT_NODE) {
                            textSources.set(node, node.nodeValue || "");
                        }
                    });
                }
            });

            observer.disconnect();
            walkTextNodes(document.body);
            observer.observe(document.body, {
                subtree: true,
                childList: true,
                characterData: true
            });
        });

        observer.observe(document.body, {
            subtree: true,
            childList: true,
            characterData: true
        });

        translate();
    }

    window.NZKI18n = {
        get language() { return currentLanguage; },
        setLanguage,
        translate,
        t: (text) => translateText(text)
    };

    // Make t() convenient for dashboard.js additions/edits.
    window.t = (text) => translateText(text);

    if (document.readyState === "loading") {
        document.addEventListener("DOMContentLoaded", init, { once: true });
    } else {
        init();
    }
})();